name: 'Draft Release Notes'
description: 'Create a draft release on GitHub based on release.yml'
author: Luca Comellini <lucacome>
inputs:
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true
  major-label:
    description: 'Label to use for major version bump'
    default: 'change'
    required: false
  minor-label:
    description: 'Label to use for minor version bump'
    default: 'enhancement'
    required: false
  notes-header:
    description: 'Header to use for changelog'
    default: ''
    required: false
  notes-footer:
    description: 'Footer to use for changelog'
    default: ''
    required: false
  variables:
    description: 'List of variables to use in the header and footer'
    default: ''
    required: false
  collapse-after:
    description: 'Number of lines required for the section to be collapsed'
    default: '0'
    required: false
  publish:
    description: 'Whether to publish the release'
    default: 'false'
    required: false
outputs:
  version:
    description: 'The version of the release'
  previous-version:
    description: 'The version of the previous release'
  release-notes:
    description: 'The release notes for the release'
  release-url:
    description: 'The URL of the release'
  release-id:
    description: 'The ID of the release'
  release-sections:
    description: 'The sections of the release in JSON format'
  release-header:
    description: 'The header of the release'
  release-footer:
    description: 'The footer of the release'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'file-text'
  color: 'green'
