name: Run build for dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.COMMIT_PAT }}

      - name: Set up Node.js 16.x
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        uses:
          actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install dependencies
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        run: npm ci

      - name: Run build
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        run: |
          npm run build
          npm run package

      - name: Commit changes
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
        id: commit
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: 'Update dist/ after build'
